-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-transcode-transcode_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE transcode
  ALTER transcode_time_addjob TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_addjob TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_startwork TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_startwork TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_success TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_success TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_error TYPE TIMESTAMPTZ;

ALTER TABLE transcode
  ALTER transcode_time_error TYPE TIMESTAMPTZ;
