-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/transcode (
  transcode_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  transcode_image_name VARCHAR(255) NOT NULL,
  transcode_key VARCHAR(48) NOT NULL,
  transcode_error CLOB NOT NULL,
  transcode_time_startwork BLOB DEFAULT NULL,
  transcode_time_success BLOB DEFAULT NULL,
  transcode_final_bitrate INTEGER NOT NULL,
  transcode_state SMALLINT DEFAULT NULL,
  transcode_touched BLOB DEFAULT NULL,
  transcode_size BIGINT DEFAULT NULL
);

CREATE INDEX transcode_key_idx ON /*_*/transcode (transcode_key);

CREATE UNIQUE INDEX transcode_name_key ON /*_*/transcode (
  transcode_image_name, transcode_key
);

CREATE INDEX transcode_state_touched ON /*_*/transcode (
  transcode_state, transcode_touched
);

CREATE INDEX transcode_state_key_touched ON /*_*/transcode (
  transcode_state, transcode_key, transcode_touched
);
