-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-transcode-drop-time_addjob.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX transcode_time_inx ON /*_*/transcode;

ALTER TABLE /*_*/transcode
  DROP transcode_time_addjob,
  DROP transcode_time_error;
