-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-transcode-transcode_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/transcode
  CHANGE transcode_time_addjob transcode_time_addjob BINARY(14) DEFAULT NULL,
  CHANGE transcode_time_startwork transcode_time_startwork BINARY(14) DEFAULT NULL,
  CHANGE transcode_time_success transcode_time_success BINARY(14) DEFAULT NULL,
  CHANGE transcode_time_error transcode_time_error BINARY(14) DEFAULT NULL;
