-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-transcode-state-size.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/transcode
  ADD transcode_state SMALLINT DEFAULT NULL,
  ADD transcode_touched BINARY(14) DEFAULT NULL,
  ADD transcode_size BIGINT DEFAULT NULL;

CREATE INDEX transcode_state_touched ON /*_*/transcode (
  transcode_state, transcode_touched
);

CREATE INDEX transcode_state_key_touched ON /*_*/transcode (
  transcode_state, transcode_key, transcode_touched
);
